### ISSUE TITLE
Loga zápasů

### ISSUE THREAD

**Issue by JKubovy** [JKubovy/plugin.video.tipsport.elh#7]
Generovat loga jednotlivých zápasů podle toho, kdo s kým hraje a kdo je domácí tým.

**Příklad:**
![example.png](https://user-images.githubusercontent.com/2380589/51437207-7631e200-1c9b-11e9-9444-08e160ab5baa.png)

**Průběh:**
- [x] Získána loga týmů
   - [x] CZ Tipsport extraliga
   - [x] SK Tipsport liga
   - [x] CZ Chance liga
- [x] Vytvoření vzoru pro finální logo zápasu
- [x] Generování finálního loga za běhu (je závislé na modulu script.module.pil)
- [x] Ukládání obrázků do dočasného adresáře (není třeba si ukládat loga zápasů dlouhodobě)
- [x] Vyřešit občasné padání Kodi při použití vygenerovaných obrázků

**TODO:**
- [x] Otestovat

**Comment by JKubovy** [comment]
Nasazeno ve verzi 0.5.8.
